force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Blockchain__c.field-meta.xml
<CustomField>
    <fullName>Blockchain__c</fullName>
    <label>Blockchain</label>
    <referenceTo>Blockchain__c</referenceTo>
    <relationshipLabel>Blocks</relationshipLabel>
    <relationshipName>Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Block__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet validated</fullName>
                <default>true</default>
                <label>Not yet validated</label>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blockchain__c/Blockchain__c.object-meta.xml
<CustomObject>
    <label>Blockchain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blockchains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blockchain__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <defaultValue>2</defaultValue>
    <inlineHelpText>The difficulty determines the amount of work (computing time) required for generating a new block on the blockchain. The higher the difficulty, the longer the computing time to find a hash that meets a specific format, like a number of leading zeros.</inlineHelpText>
    <label>Difficulty</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blockchain__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>The reward (e.g. number of crypto coins) a miner receives after generating a new block. This is the incentive for miners to provide computing time for mining a hash to generate a new block.</inlineHelpText>
    <label>Reward</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Total_Amount_Received__c - Total_Amount_Sent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Blockchain__c.field-meta.xml
<CustomField>
    <fullName>Blockchain__c</fullName>
    <label>Blockchain</label>
    <referenceTo>Blockchain__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Blockchain__c.field-meta.xml
<CustomField>
    <fullName>Blockchain__c</fullName>
    <label>Blockchain</label>
    <referenceTo>Blockchain__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/From_Participant__c.field-meta.xml
<CustomField>
    <fullName>From_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Transactions - Sent</relationshipLabel>
    <relationshipName>Transactions_Sent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/To_Participant__c.field-meta.xml
<CustomField>
    <fullName>To_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Transactions - Received</relationshipLabel>
    <relationshipName>Transactions_Received</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Transaction_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Validated</fullName>
    </customValue>
    <customValue>
        <fullName>Committed</fullName>
    </customValue>
    <masterLabel>Transaction Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Transaction_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Transfer</fullName>
        <default>true</default>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>Reward</fullName>
    </customValue>
    <masterLabel>Transaction Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BlockchainControllerTest.cls
@isTest
private class BlockchainControllerTest {
    
    @isTest
    static void testBlockchain(){
        // Create a blockchain for digicoins:
        Blockchain__c digicoin = new Blockchain__c();
        digicoin.Name = 'Digicoin';
        digicoin.Difficulty__c = '1';
        digicoin.Reward__c = 2;
        Insert digicoin;
        
        // Add participants:
        Participant__c marc = new Participant__c(Blockchain__c = digicoin.Id, Name = 'Marc Benioff');
        Participant__c elon = new Participant__c(Blockchain__c = digicoin.Id, Name = 'Elon Musk');
        Participant__c tim  = new Participant__c(Blockchain__c = digicoin.Id, Name = 'Tim Cook');
        Insert new List<Participant__c>{marc, elon, tim};
        
        // Create the Genesis block:
        BlockchainController.createGenesisBlock(digicoin.Id);
        List<Block__c> blocks = BlockchainController.getBlocks(digicoin.Id);
        System.assertEquals('Block 0 (Genesis Block)', blocks[0].Name);
        
        // Execute some transactions:
        Double fromMarcToElon = 10;
        Double fromElonToTim = 4;
        Transaction__c trans1 = new Transaction__c(Blockchain__c = digicoin.Id, From_Participant__c = marc.Id, To_Participant__c = elon.Id, Amount__c = fromMarcToElon/2);
        Transaction__c trans2 = new Transaction__c(Blockchain__c = digicoin.Id, From_Participant__c = marc.Id, To_Participant__c = elon.Id, Amount__c = fromMarcToElon/2);
        Transaction__c trans3 = new Transaction__c(Blockchain__c = digicoin.Id, From_Participant__c = elon.Id, To_Participant__c = tim.Id, Amount__c = fromElonToTim);
        Insert new List<Transaction__c>{trans1, trans2, trans3};
        
        // Add/mine a block:
        BlockchainController.addBlock(digicoin.Id, marc.Id);
        
        // Validate that the block has been added to the blockchain:
        blocks = BlockchainController.getBlocks(digicoin.Id);
        System.assertEquals(2, blocks.size());
        Block__c block1 = blocks[1];
        System.assertNotEquals(null, block1.Hash__c);
        System.assertEquals(3, block1.Number_of_Transactions__c);
        
        // Validate that the status of the two transfer transactions is updated to 'Committed'
        // and that a pending reward transaction is created for Marc Benioff:
        List<Transaction__c> transactions = getTransactions();
        System.assertEquals(4, transactions.size());
        for (Transaction__c trans : transactions){
            if (trans.To_Participant__c == elon.Id){
                System.assertEquals('Transfer', trans.Type__c);
                System.assertEquals('Committed', trans.Status__c);
            }
            else if (trans.To_Participant__c == tim.Id){
                System.assertEquals('Transfer', trans.Type__c);
                System.assertEquals('Committed', trans.Status__c);
            }
            else {
                System.assertEquals(marc.Id, trans.To_Participant__c);
                System.assertEquals('Reward', trans.Type__c);
                System.assertEquals('Pending', trans.Status__c);
            }
        }
        
        // Validate that the balance of the participants is updated:
        for (Participant__c participant : getParticipants()){
            switch on participant.Name {
                when 'Marc Benioff' {
                    System.assertEquals(-fromMarcToElon, participant.Balance__c);
                }
                when 'Elon Musk' {
                    System.assertEquals(fromMarcToElon-fromElonToTim, participant.Balance__c);
                }
                when 'Tim Cook' {
                    System.assertEquals(fromElonToTim, participant.Balance__c);
                }
            }
        }
        
        // Check that the blockchain has not been tempered or hacked:
        List<BlockchainController.BlockValidationResult> resultList = BlockchainController.validateBlockchain(digicoin.Id);
        for (BlockchainController.BlockValidationResult result : resultList){
            System.assert(result.isValid);
        }
        
        // Change the amount of an existing transaction:
        trans1.Amount__c += 0.1;
        Update trans1;
        
        // Validate that this hack is reflected in the blockchain:
        resultList = BlockchainController.validateBlockchain(digicoin.Id);
        for (BlockchainController.BlockValidationResult result : resultList){
            System.assert(!result.isValid);
        }
    }
    
    static List<Transaction__c> getTransactions(){
        return [SELECT Id, Type__c, Status__c, From_Participant__c, To_Participant__c FROM Transaction__c];
    }
    
    static List<Participant__c> getParticipants(){
        return [SELECT Id, Name, Balance__c FROM Participant__c];
    }
}