force-app/main/default/objects/Block__c/Block__c.object-meta.xml
<CustomObject>
    <label>Block</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Block__c/fields/Blockchain__c.field-meta.xml
<CustomField>
    <fullName>Blockchain__c</fullName>
    <label>Blockchain</label>
    <referenceTo>Blockchain__c</referenceTo>
    <relationshipLabel>Blocks</relationshipLabel>
    <relationshipName>Blocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Block__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Block__c/fields/Nonce__c.field-meta.xml
<CustomField>
    <fullName>Nonce__c</fullName>
    <label>Nonce</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Block__c/fields/Previous_Hash__c.field-meta.xml
<CustomField>
    <fullName>Previous_Hash__c</fullName>
    <label>Previous Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Blockchain__c/Blockchain__c.object-meta.xml
<CustomObject>
    <label>Blockchain</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blockchains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transaction Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Block</label>
    <referenceTo>Block__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Blockchain__c.field-meta.xml
<CustomField>
    <fullName>Blockchain__c</fullName>
    <label>Blockchain</label>
    <referenceTo>Blockchain__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/From_Participant__c.field-meta.xml
<CustomField>
    <fullName>From_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Transactions - Sent</relationshipLabel>
    <relationshipName>Transactions_Sent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/To_Participant__c.field-meta.xml
<CustomField>
    <fullName>To_Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Transactions - Received</relationshipLabel>
    <relationshipName>Transactions_Received</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Transaction_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Transaction_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Transfer</fullName>
        <default>true</default>
        <label>Transfer</label>
    </customValue>
    <customValue>
        <fullName>Reward</fullName>
    </customValue>
    <masterLabel>Transaction Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Block.cls
public inherited sharing class Block {
    
    public Integer index { get; set; }
    public DateTime timestamp { get; set; }
    public String previousHash { get; set; }
    public String hash { get; private set; }
    public Integer nonce { get; set; }
    public String data { get; private set; }
    public Integer numberOfTransactions { get; private set; }
    
    public Block(){
        timestamp = Datetime.now();
        index = 0;
        numberOfTransactions = 0;
        nonce = 0;
    }
    
    public String calculateHash(){
        Blob input = Blob.valueOf(timestamp + previousHash + data + nonce);
        Blob outputBytes = Crypto.generateMac('HmacSHA256', input, Blob.valueOf('key'));
        return EncodingUtil.base64Encode(outputBytes);
    }
    
    public void mineHash(Integer difficulty){
        String leadingZeros = '';
        leadingZeros = leadingZeros.rightPad(difficulty, '0');
        while (hash == null || !hash.startsWith(leadingZeros)){
            nonce++;
            hash = calculateHash();
        }
    }
    
    public Block__c addToBlockchain(Id blockchainId){
        Block__c block = new Block__c();
        block.Index__c = index;
        block.Name = 'Block ' + index;
        if (index == 0) block.Name += ' (Genesis Block)';
        block.Blockchain__c = blockchainId;
        block.Timestamp__c = timestamp;
        block.Previous_Hash__c = previousHash;
        block.Hash__c = hash;
        block.Nonce__c = nonce;
        block.Number_of_Transactions__c = numberOfTransactions;
        Insert block;
        return block;
    }

    public void setTransactionData(List<Transaction__c> transactions){
        List<Trans> transactionData = new List<Trans>();
        for (Transaction__c trans : transactions){
            transactionData.add(new Trans(trans.From_Participant__c, trans.To_Participant__c, trans.Amount__c, trans.Type__c, trans.CreatedDate));
        }
        data = JSON.serialize(transactionData);
        numberOfTransactions = transactions.size();
    }

    private class Trans {
        String senderId;
        String receiverId;
        String amount;
        String type;
        String createdDate;

        public Trans(Id senderId, Id receiverId, Decimal amount, String type, Datetime createdDate){
            this.senderId = senderId;
            this.receiverId = receiverId;
            this.amount = amount.format();
            this.type = type;
            this.createdDate = String.valueOf(createdDate);
        }
    }
    
}